#!/bin/sh

#echo AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID >> .env
echo DOCKER_REGISTRY=$DOCKER_REGISTRY >> .env
echo CI_PIPELINE_IID=$CI_PIPELINE_IID >> .env
echo APP_NAME=$APP_NAME >> .env
echo IMAGE=$DOCKER_REGISTRY/$APP_NAME/$CI_PIPELINE_IID >> .env
echo CI_REGISTRY_USER=$CI_REGISTRY_USER >> .env
echo CI_REGISTRY_PASSWORD=$CI_REGISTRY_PASSWORD >> .env
echo CI_REGISTRY_URL=$CI_REGISTRY_URL >> .env
